import Foundation

// The generated source lives in SwiftPM's build directory. Assets are compiled into
// the executable rather than a resource bundle that an SSH installation could omit.
let arguments = Array(CommandLine.arguments.dropFirst())
guard arguments.count == 4 else {
    fatalError("usage: EmbedWebAssets <output.swift> <index.html> <app.js> <style.css>")
}
let names = ["html", "script", "style"]
var source = "// Generated by EmbedWebAssets. Edit Sources/MuxifySimulatorServer/Web instead.\nimport Foundation\n\nextension WebAssets {\n"
for (name, path) in zip(names, arguments.dropFirst()) {
    let data = try Data(contentsOf: URL(fileURLWithPath: path))
    source += "    static let \(name) = Data(base64Encoded: \"\(data.base64EncodedString())\")!\n"
}
source += "}\n"
try source.write(toFile: arguments[0], atomically: true, encoding: .utf8)
